# [Required]
# Basic component information
repo: pydm-mps
organization: ad-build-test
url: https://github.com/ad-build-test/pydm-mps
description: Pydm mps displays taken from /afs/slac/g/cd/swe/git/repos/slac/pydm_displays/mps.git

# [Optional] Docker image for build pods
# image: ghcr.io/ad-build-test/rocky9-env:latest

# [Optional] Build command — skip if no build step needed
# build:
#   command: "pip install -r requirements.txt"

# [Optional] Deployment playbook
deploy:
  playbook: pydm_module/pydm_deploy.yml
  